### ISSUE TITLE
Support for use as a drop-in replacement for RPi.GPIO for gpiozero

### ISSUE THREAD

**Issue by theyoyojo** [underground-software/libgpiod#10]
In response to: https://github.com/gpiozero/gpiozero/issues/840

**Comment by bennuttall** [comment]
In particular, to be a drop-in replacement, there would need to be a "pin factory" implementation, which normalises the functionality of a pin library into a standard set of methods. The RPi.GPIO one is here: https://github.com/gpiozero/gpiozero/blob/master/gpiozero/pins/rpigpio.py

More info: https://gpiozero.readthedocs.io/en/latest/api_pins.html

**Comment by theyoyojo** [comment]
A test-driven way we could approach this feature would be to integrate a version of that file into our testing system as we move towards API-equivalence with RPi.GPIO.

**Comment by theyoyojo** [comment]
I think that we are getting close to full compatibility with #23. #25, and #26

**Comment by lurch** [comment]
Nice, I'll try to have a look at it this weekend (if I remember!) :+1:

**Comment by theyoyojo** [comment]
Oops, looks like I forgot another constant:

```
>>> import gpiozero.pins.rpigpio as rpigpio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rpi/python3-libgpiod-rpi/lib/python3.7/site-packages/gpiozero/pins/rpigpio.py", line 91, in <module>
    class RPiGPIOPin(LocalPiPin):
  File "/home/rpi/python3-libgpiod-rpi/lib/python3.7/site-packages/gpiozero/pins/rpigpio.py", line 104, in RPiGPIOPin
    'serial':  GPIO.SERIAL,
AttributeError: module 'RPi.GPIO' has no attribute 'SERIAL'
```

**Comment by theyoyojo** [comment]
Alright it imports correctly now, but gpiozero now throws the following when I try to evaluate PiFactory.pi_info()
```
>>> import gpiozero.pins.rpigpio as rpigpio
>>> fac = rpigpio.LocalPiFactory()
>>> fac.pi_info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rpi/.local/lib/python3.7/site-packages/gpiozero/pins/__init__.py", line 188, in <lambda>
    lambda self: self._get_pi_info(),
  File "/home/rpi/.local/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 120, in _get_pi_info
    self._info = pi_info(self._get_revision())
  File "/home/rpi/.local/lib/python3.7/site-packages/gpiozero/pins/local.py", line 109, in _get_revision
    raise PinUnknownPi('unable to locate Pi revision in /proc/device-tree or /proc/cpuinfo')
gpiozero.exc.PinUnknownPi: unable to locate Pi revision in /proc/device-tree or /proc/cpuinfo
```

**Comment by bennuttall** [comment]
Are you able to get the revision code another way? We ought to patch that. @lurch any ideas for doing that outside of Raspbian?

**Comment by theyoyojo** [comment]
mistakenly closed instead of #37

**Comment by theyoyojo** [comment]
About to look into revision code issue. Just released RPi.GPIO2 0.3.0a2 to PyPi so people can `pip install` a version that is importable by gpiozero

**Comment by theyoyojo** [comment]
On one of the pigpio issues: https://github.com/joan2937/pigpio/issues/340,
@guymcswain links to the following hack: https://www.raspberrypi.org/forums/viewtopic.php?p=1428987#p1428987

**Comment by theyoyojo** [comment]
One way to do might be to have a table mapping values of `cat /proc/device-tree/model` to revision strings, perhaps something like:

```
diff --git a/gpiozero/pins/local.py b/gpiozero/pins/local.py
index 1c40c47..df4b678 100644
--- a/gpiozero/pins/local.py
+++ b/gpiozero/pins/local.py
@@ -61,6 +61,10 @@ from ..devices import Device, SharedMixin
 from ..output_devices import OutputDevice
 from ..exc import DeviceClosed, PinUnknownPi, SPIInvalidClockMode
 
+REVISION_TABLE = {
+    "Raspberry Pi 3 Model B": hex(0xa22082),
+}
+
 
 class LocalPiFactory(PiFactory):
     """
@@ -98,6 +102,14 @@ class LocalPiFactory(PiFactory):
         except IOError as e:
             if e.errno != errno.ENOENT:
                 raise e
+        try:
+            with io.open('/proc/device-tree/model', 'r') as f:
+                modelstr = f.readline()[:-1]
+                revision = REVISION_TABLE[modelstr]
+        except (IOError, KeyError) as e:
+            if not isinstance(e, IOError) or e.errno != errno.ENOENT:
+                raise e
             with io.open('/proc/cpuinfo', 'r') as f:
                 for line in f:
                     if line.startswith('Revision'):

```

**Comment by theyoyojo** [comment]
Using this patch to gpiozero, I was able to get gpiozerocli.pinout.main() to work with RPi.GPIO2 0.3.0a2
