### ISSUE TITLE
Correct RPi.GPIO syntax results in an error

### ISSUE THREAD

**Issue by theyoyojo** [underground-software/libgpiod#6]
Version: [Exodus](https://github.com/underground-software/python3-libgpiod-rpi/releases/tag/v0.2)

Reproducer:
```python
import RPi.GPIO as GPIO
import time
def callback_one(pin):
    print("CALLBACK")
GPIO.setmode(GPIO.BCM)
GPIO.setup(21, GPIO.IN, GPIO.PUD_OFF)
GPIO.add_event_detect(21, GPIO.RISING, callback_one, 1)
input()
GPIO.cleanup()
```

Error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.7/site-packages/RPi/_GPIO.py", line 431, in poll_thread
    if wait_for_edge(channel, edge, bouncetime, 10):
  File "/usr/lib64/python3.7/site-packages/RPi/_GPIO.py", line 415, in wait_for_edge
    event = _State.lines[channel].event_read()
PermissionError: [Errno 1] Operation not permitted
```

Need to look into this further. We should make sure the tests cover this edge case.

**Comment by theyoyojo** [comment]
Just looked at this again and I think I know what this issue is
